version: '2'
services:
  #|-----------------|#
  #| Apache with php |#
  #|-----------------|#
#  web:
#     image: tutum/apache-php
#     restart: always
#     ports:
#        - "8080:80"
#     volumes:
#        - .:/var/www
#        - ./docker/config/php.ini:/etc/php5/apache2/conf.d/40-custom.ini
#        - ./docker/config/apache:/etc/apache2/sites-enabled
#     environment:
#        - ALLOW_OVERRIDE=true
#     links:
#        - db:db
#        - maildev:maildev

  #|--------------|#
  #| Nginx server |#
  #|--------------|#
#  web:
#     image: nginx
#     ports:
#        - "8080:80"
#     volumes:
#        - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
#        - .:/var/www/html
#     links:
#        - php7:php7

  #|--------------|#
  #| Apache       |#
  #|--------------|#
#  web:
#     restart: always
#     build: ./docker/apache
#     ports:
#        - "80:80"
#     volumes:
#        - .:/var/www
#        - ./docker/config/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
#        - ./docker/config/apache:/etc/apache2/sites-enabled
#     environment:
#        - ALLOW_OVERRIDE=true
#     links:
#        - db:db
#        - maildev:maildev

  #|--------------|#
  #| Php apache   |#
  #|--------------|#

  web:
    build: ./docker/php7.1-apache
    ports :
     - "81:80"
    volumes:
     - .:/var/www/html
     - ./docker/config/php.ini:/usr/local/etc/php/php.ini
    links:
     - db:db
     - maildev:maildev

#  web:
#      image: php:7.1-apache
#      restart: always
#      ports :
#       - "8080:80"
#      volumes:
#       - .:/var/www/html
#       - ./docker/config/php.ini:/usr/local/etc/php/php.ini
#      links:
#       - db:db
#       - maildev:maildev

  #|--------------|#
  #| Php fpm      |#
  #|--------------|#

  #php5.6:
  #   build: php5.6-fpm
  #   volumes:
  #      - .:/var/www/html
  #      - ./docker/config/php.ini:/usr/local/etc/php/php.ini
  #   links:
  #      - db:db
  #      - maildev:maildev
  #      - blackfire:blackfire
  #   command: php-fpm --allow-to-run-as-root
  #   privileged: true

#  php7:
#     build: ./docker/php7.0-fpm
#     volumes:
#        - .:/var/www/html
#        - ./docker/config/php.ini:/usr/local/etc/php/php.ini
#     links:
#        - db:db
#        - maildev:maildev
#     command: php-fpm --allow-to-run-as-root
#     privileged: true

  #|--------------|#
  #| DB           |#
  #|--------------|#

  db:
     image: mysql
     restart: always
     volumes:
        - "./.data/db:/var/lib/mysql"
     environment:
        - MYSQL_ROOT_PASSWORD=root

  maildev:
     image: djfarrelly/maildev
     restart: always
     ports:
        - "1088:80"

  #blackfire:
  #   image: blackfire/blackfire
  #   restart: always
  #   environment:
  #      - BLACKFIRE_SERVER_ID=95f4f00d-b4e1-455d-ba44-a063b9961016
  #      - BLACKFIRE_SERVER_TOKEN=5a95186db368ab11b202caff4c0c342ce611d4a7e12a7a8560a906b2fd918852

  #varnish:
  #   image: jacksoncage/varnish
  #   links:
  #      - web:web
  #   volumes:
  #      - /var/www/docker/config/varnish/default.vcl:/etc/varnish/default.vcl
  #   ports:
  #      - "80:80"