#!/usr/bin/env php
<?php

set_time_limit(0);

define('ROOT',__DIR__);
define ('WEBROOT', str_replace('index.php', '', $_SERVER['SCRIPT_NAME']));
require ROOT.'/vendor/autoload.php';

$jet = new \Jet\App();
$cli = $jet->getConsole();
$cli->run();